# Site settings
title: "OMAC"
email: "secretary@OttawaMandarinAlliance.ca"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

wechat: "omac"
facebookgroup: "ottawamac"
address: "550 Codd’s Rd. Ottawa ON K1K 2G8"


# Build settings
markdown: kramdown
