- title: 我们的信仰
  icon: diamond
  link: 
  content: 我信上帝，全能的父，創造天地的主。 我信我主耶穌基督，上帝獨生的子。 因聖靈感孕，由童貞女馬利亞所生； 在本丟彼拉多手下受難，被釘於十字架上， 受死，埋葬；降在陰間；第三天從死人中復活；升天，坐在全能父上帝的右邊； 將來必從那裡降臨，審判活人死人。 我信聖靈。 我信聖而公之教會。 我信聖徒相通。 我信罪得赦免。 我信身體復活。 我信永生。阿們。

- title: 我们的历史
  icon: history
  link: history.html
  content: 渥太华国语宣道会成立於1995年。这是一间不分背景，经历，年龄而同习真理，彼此关怀，操练服事，传讲福音，荣耀敬拜主的信仰纯正的教会。

- title: 我们的牧者
  icon: users
  link: pastor.html
  content: 陈牧师在渥太华国语宣道会受洗，受神呼召献身，进神学院学习；2007年开始在国语宣道会服侍至今。他带领教会与东门宣道会在青少年，幼儿教育和建堂等方面合作，为渥太华华人家庭建立属灵的家。

- title: 异象使命
  icon: globe
  link:
  content: 渥太华国语宣道会的异象是要装备信徒成为基督的门徒, 致力在家庭, 学校, 社区, 工作场所和世界各地拓展神国事工<li>帮助信徒、门徒与神建立亲密的关系,并且每天活出神的话语</li><li>培养信徒、门徒对教会的归属感, 并且委身其中</li><li>装备信徒、门徒用福音及行动关怀其所属的社区与群体。</li>
